# Makefile
#----------------------------------------------------------------------------------------
#
#  Project: PTPSecureServer 1.00
#
#  License: Boost Software License - Version 1.0 - August 17th, 2003
#
#            see http://www.boost.org/LICENSE_1_0.txt or the local copy
#
#  Copyright (c) 2024 Sergey Strukov. All rights reserved.
#
#----------------------------------------------------------------------------------------

LIGHT_FORGE ?= ~/LightForge

Server = $(LIGHT_FORGE)/build/ccore/CCore/PTPSecureServer/CCore-PTPSecureServer.exe

.PHONY : run

run:
	$(Server) Config.ddl


